version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  docker-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes: 
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=shashi
      - MONGO_PASSWORD=shashi
      - SESSION_SECRET=secret
    command: npm run dev

  mongo-app:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shashi
      - MONGO_INITDB_ROOT_PASSWORD=shashi

  