version: "3"
services:
  docker-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes: 
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=shashi
      - MONGO_PASSWORD=shashi
    command: npm run dev

  