version: "3"
services:
  nginx:
    ports:
      - "80:80"
  docker-app:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=production
    command: node app.js