version: "3"
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  docker-app:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo-app
    # env_file:
    #   - ./.env

  mongo-app:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shashi
      - MONGO_INITDB_ROOT_PASSWORD=shashi
    volumes:
      - mongo-db:/data/db

  redis-app:
    image: redis
  
volumes:
  mongo-db: